accounts/views.py
from flask import Blueprint, render_template, redirect, flash, url_for,  request
from flask_login import logout_user, login_required

from accounts.forms import RegisterForm, LoginForm

accounts = Blueprint('accounts', __name__,
                     template_folder='templates',
                     static_folder='../assets')


@accounts.route('/login', methods=['GET', 'POST'])
def login():
    """ 登录页面 """
    form = LoginForm()
    next_url = request.values.get('next', url_for('qa.index'))
    print(next_url)
    if form.validate_on_submit():
        user = form.do_login()
        if user:
            # 4、跳转到指定页面或首页
            flash('{}，欢迎登录在线问答系统！'.format(user.nickname), 'success')
            return redirect(next_url)
        else:
            flash('登录失败，请稍后重试', 'danger')
    return render_template('login.html', form=form, next_url=next_url)


@accounts.route('/logout')
def logout():
    """ 退出登录 """
    logout_user()
    flash('期待下一次相见！', 'success')
    return redirect(url_for('accounts.login'))


@accounts.route('/register', methods=['GET', 'POST'])
def register():
    """ 注册 """
    form = RegisterForm()
    if form.validate_on_submit():
        user_obj = form.register()
        if user_obj:
            # 3、跳转到成功页面
            flash('注册成功，请登录！', 'success')
            return redirect(url_for('accounts.login'))
        else:
            flash('注册失败，请稍后再试。', 'danger')
    return render_template('register.html', form=form)


@accounts.route('/mine')
@login_required
def mine():
    """ 个人中心 """
    return render_template('mine.html')


qa/views.py
from flask import Blueprint, render_template, request, abort, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user

from conf import Config
from models import Question, Answer, AnswerComment, db
from qa.forms import WriteQuestionForm, WriteAnswerForm

qa = Blueprint('qa', __name__,
               template_folder='templates',
               static_folder='../assets')


@qa.route('/')
def index():
    """ 首页 回答列表 """
    page = int(request.args.get('page', 1))
    page_data = Answer.query.filter_by(is_valid=True).order_by(Answer.updated_at.desc()).paginate(page=page, per_page=Config.PER_PAGE)

    return render_template('index.html', page_data=page_data)


@qa.route('/follow_page')
def follow_page():
    """ 关注 问题列表 """
    page = int(request.args.get('page', 1))
    page_data = Question.query.filter_by(is_valid=True).order_by(Question.updated_at.desc()).paginate(page=page, per_page=Config.PER_PAGE)
    return render_template('follow_page.html', page_data=page_data)


@qa.route('/follow')
def follow():
    """ 关注 """
    page = int(request.args.get('page', 1))
    page_data = Question.query.filter_by(is_valid=True).order_by(Question.updated_at.desc()).paginate(page=page,
                                                                                                      per_page=Config.PER_PAGE)
    return render_template('follow.html', page_data=page_data)


@qa.route('/qa/list')
def question_list():
    """ 查询问题数据列表 """
    """
    json
    {
        'code': 0,
        'data': '',
    }
    """
    try:
        page = int(request.args.get('page', 1))
        page_data = Question.query.filter_by(is_valid=True).order_by(Question.updated_at.desc()).paginate(page=page, per_page=Config.PER_PAGE)
        data = render_template('qa_list.html', page_data=page_data)
        code = 0
    except Exception as e:
        print(e)
        data = ''
        code = 1
    return {'code': code, 'data': data}


@qa.route('/write', methods=['GET', 'POST'])
@login_required
def write():
    """ 写文章，提问 """
    form = WriteQuestionForm()
    if form.validate_on_submit():
        try:
            que_obj = form.save()
            if que_obj:
                flash('问题发布成功', 'success')
                return redirect(url_for('qa.detail', q_id=que_obj.id))
        except Exception as e:
            print(e)
            flash('问题发布失败，请稍后重试', 'danger')
    return render_template('write.html', form=form)


@qa.route('/detail/<int:q_id>', methods=['GET', 'POST'])
def detail(q_id):
    """ 问题详情 """
    # 1、查询问题信息
    question = Question.query.get(q_id)
    if not question.is_valid:
        abort(404)
    # 2、展示第一条回答信息
    answer = question.answer_list.filter_by(is_valid=True).first()

    # 添加回答
    form = WriteAnswerForm()
    if form.validate_on_submit():
        try:
            if not current_user.is_authenticated:
                flash('您尚未登录,请先登录！', 'danger')
                return redirect(url_for('accounts.login'))
            answer_obj = form.save(question=question)
            print(answer_obj)
            if answer_obj:
                flash('回答问题成功', 'success')
                return redirect(url_for('qa.detail', q_id=q_id))
        except Exception as e:
            print(e)
            print(form.errors)
            flash('回答问题失败，稍候再试', 'danger')

    return render_template('detail.html', question=question, answer=answer, form=form)


@qa.route('/comments/<int:answer_id>', methods=['GET', 'POST'])
def comments(answer_id):
    """ 评论 """
    answer = Answer.query.get(answer_id)
    if request.method == 'POST':
        # 添加评论，保存到数据库
        try:
            if not current_user.is_authenticated:
                result = {'code': 1, 'message': '请登录'}
                return jsonify(result), 401
            # 获取数据
            content = request.form.get('content', '')
            reply_id = request.form.get('reply_id', None)
            question = answer.question
            comment_obj = AnswerComment(content=content, user=current_user, answer=answer, reply_id=reply_id, question=question)
            db.session.add(comment_obj)
            db.session.commit()
            result = {'code': 0, 'message': '评论成功'}
            return jsonify(result), 201
        except Exception as e:
            result = {'code': 2, 'message': '服务器正忙，请稍后重试'}
            return jsonify(result), 500
    else:
        try:
            # 获取评论列表
            page = int(request.args.get('page', 1))
            page_data = answer.comment_list().paginate(page=page, per_page=Config.PER_PAGE)
            data = render_template('comments.html', page_data=page_data, answer=answer)
            return jsonify({'code': 0, 'data': data, 'meta': {'page': page}}), 200
        except Exception as e:
            print(e)
            return jsonify({'code': 1, 'data': '', 'message': '服务器正忙，请稍后再试！'}), 500


@qa.route('/comment/love/<int:comment_id>', methods=['POST'])
def comment_love(comment_id):
    """ 为评论点赞 """
    try:
        if not current_user.is_authenticated:
            return '', 401
        comment_obj = AnswerComment.query.get(comment_id)
        comment_obj.love_count += 1
        db.session.add(comment_obj)
        db.session.commit()
    except Exception as e:
        abort(500)
    return '', 201



templates/components/classified_menu.html
<!-- 分类菜单 -->
<div class="cls-menu-ls">
    <a href="{{ url_for('qa.index') }}" class="active">推荐</a>
    <a href="{{ url_for('qa.follow') }}">关注</a>
    <a href="#">热榜</a>
</div>
<!-- //分类菜单 -->

templates/components/flash_messages.html
{# flash 消息 #}
<!-- 消息通知区域 -->
{% for category, message in get_flashed_messages(with_categories=True) %}
<div class="alert alert-{{ category }} alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    {% autoescape false %}
    <span>{{ message }}</span>
    {% endautoescape %}
</div>
{% endfor %}
<!-- // 消息通知区域 -->

templates/components/layout_header_nav.html
<!-- 顶部导航 -->
<div class="layout-header">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#id-index-banner"
                        aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">在线问答系统</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="id-index-banner">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('qa.index') }}">首页 <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">话题</a></li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="搜索话题">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li>
                            <!-- 使用flask-login登录 -->
                            <a href="#">您好，{{ current_user.nickname }}</a>
                        </li>
                        <li><a href="#">提问</a></li>
                        <li><a href="#">消息<span class="badge">4</span></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">个人中心 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="./mine.html">我的主页</a></li>
                                <li><a href="./mine.html">设置</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for('accounts.logout') }}">退出</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li>
                            <a href="{{ url_for('accounts.login') }}">登录</a>
                        </li>
                        <li>
                            <a href="{{ url_for('accounts.register') }}">注册</a>
                        </li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>
<!-- // 顶部导航 -->